[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 115200

; --- THIS IS THE FIX ---
board_build.arduino.memory_type = opi_opi 
board_build.flash_mode = opi
; -----------------------

board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
board_build.partitions = default_8MB.csv
board_build.filesystem = littlefs