[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; The magic trick to fit a 1MB song on a 4MB chip!
board_build.partitions = no_ota.csv
board_build.filesystem = littlefs

; Automatically download the Bluetooth library
lib_deps =
    https://github.com/pschatzmann/ESP32-A2DP.git